### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by etoledom** [etoledom/Heyou#6]
### v0.1.0
- [x] Elements:
  - [x] Title
  - [x] Subtitle
  - [x] Description
  - [x] Image
- [x] Buttons:
  - [x] Default
  - [x] Main (call to action)
  - [x] Destructive
  - [x] Cancel
 
### v0.2.0
- [ ] Content scrollable when bigger than controller's root view
- [ ] Revise style customization api
- [ ] Horizontal buttons layout
